- hosts: zabbix_agent
  remote_user: root
  vars:
    download_folder: /home/zabbixuser/zabbix
    zabbix_agent_archive: "{{download_folder}}/zabbix_agents_3.0.4.linux2_6_23.i386.tar.gz"
    zabbix_agent: "{{download_folder}}/agent_3.0.4"
  tasks:
    - name: add group
      group: name=zabbixuser state=present
    - name: Add deployment user
      action: user name=zabbixuser group=zabbixuser state=present
    - name: Creates directory
      file: path=/home/zabbixuser/zabbix owner=zabbixuser group=zabbixuser state=directory
    - name: Creates agent directory
      file: path=/home/zabbixuser/zabbix/agent_3.0.4 owner=zabbixuser group=zabbixuser state=directory
    - name: create agent configration directory
      file: path=/etc/zabbix/ owner=zabbixuser group=zabbixuser state=directory
    - name: tar.gz download
      shell: scp root@10.0.2.15:/root/zabbix/zabbix_agents_3.0.4.linux2_6_23.i386.tar.gz {{download_folder}}/zabbix_agents_3.0.4.linux2_6_23.i386.tar.gz
    - name: Unarchive source
      command: "tar -zxf {{zabbix_agent_archive}} -C {{zabbix_agent}}"
    - name: copy config file
      command: cp /home/zabbixuser/zabbix/agent_3.0.4/conf/zabbix_agentd.conf /etc/zabbix/
    - name: copy agent to execution directory
      command: cp /home/zabbixuser/zabbix/agent_3.0.4/sbin/zabbix_agentd /usr/sbin
    - name: copy zabbix_get
      command: cp /home/zabbixuser/zabbix/agent_3.0.4/bin/zabbix_get /usr/bin
    - name: copy  zabbix_sender
      command: cp /home/zabbixuser/zabbix/agent_3.0.4/bin/zabbix_sender /usr/bin
    - name: copy service file
      shell: scp root@10.0.2.15:/root/share/zabbix-agent /etc/init.d/zabbix-agent
